# Generated by Django 5.2.8 on 2025-11-11 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127, null=True)),
                ('last_name', models.CharField(max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='test', max_length=127, null=True)),
                ('description', models.TextField(max_length=2047, null=True)),
                ('price', models.IntegerField(default=99)),
                ('publisher', models.CharField(max_length=127, null=True)),
                ('is_released', models.BooleanField(default=True, null=True)),
                ('release_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('language', models.CharField(choices=[('0', 'farsi'), ('1', 'arabic'), ('2', 'english')], max_length=1)),
                ('categories', models.ManyToManyField(to='base.category')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.writer')),
            ],
        ),
    ]
