# Generated by Django 5.2.8 on 2025-12-02 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_book_rate_alter_book_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, null=True, verbose_name='ویژگی')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='book',
            name='writer',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2047, null=True, verbose_name='متن')),
                ('suggestion', models.CharField(choices=[('0', 'I suggest this Product'), ('1', "I don't suggest this Product"), ('2', 'I have no idea.')], max_length=1, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='عنوان')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='قیمت')),
                ('size', models.CharField(choices=[('0', 'M'), ('1', 'L'), ('2', 'XL'), ('3', 'XXL')], max_length=1, null=True, verbose_name='سایز')),
                ('description', models.TextField(max_length=2047, null=True, verbose_name='توضیحات')),
                ('static_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='قیمت تخفیف')),
                ('percent_dicount', models.IntegerField(blank=True, null=True)),
                ('product_features', models.ManyToManyField(to='base.productfeature')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
