# Generated by Django 5.2.8 on 2025-12-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_productfeature_remove_book_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='suggestion',
            field=models.CharField(choices=[('0', 'I suggest this Product'), ('1', "I don't suggest this Product"), ('2', 'I have no idea.')], max_length=1, null=True, verbose_name='خلاصه'),
        ),
    ]
