# Generated by Django 5.2.8 on 2025-12-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_comment_product_alter_comment_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Product_images/'),
        ),
    ]
